// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/loginv1/login.proto

package loginv1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	loginv1 "golang_grpc_mysql/proto/loginv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// LoginServiceName is the fully-qualified name of the LoginService service.
	LoginServiceName = "proto.LoginService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LoginServiceLoginProcedure is the fully-qualified name of the LoginService's Login RPC.
	LoginServiceLoginProcedure = "/proto.LoginService/Login"
)

// LoginServiceClient is a client for the proto.LoginService service.
type LoginServiceClient interface {
	Login(context.Context, *connect_go.Request[loginv1.LoginRequest]) (*connect_go.Response[loginv1.LoginResponse], error)
}

// NewLoginServiceClient constructs a client for the proto.LoginService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLoginServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) LoginServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &loginServiceClient{
		login: connect_go.NewClient[loginv1.LoginRequest, loginv1.LoginResponse](
			httpClient,
			baseURL+LoginServiceLoginProcedure,
			opts...,
		),
	}
}

// loginServiceClient implements LoginServiceClient.
type loginServiceClient struct {
	login *connect_go.Client[loginv1.LoginRequest, loginv1.LoginResponse]
}

// Login calls proto.LoginService.Login.
func (c *loginServiceClient) Login(ctx context.Context, req *connect_go.Request[loginv1.LoginRequest]) (*connect_go.Response[loginv1.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// LoginServiceHandler is an implementation of the proto.LoginService service.
type LoginServiceHandler interface {
	Login(context.Context, *connect_go.Request[loginv1.LoginRequest]) (*connect_go.Response[loginv1.LoginResponse], error)
}

// NewLoginServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLoginServiceHandler(svc LoginServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	loginServiceLoginHandler := connect_go.NewUnaryHandler(
		LoginServiceLoginProcedure,
		svc.Login,
		opts...,
	)
	return "/proto.LoginService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LoginServiceLoginProcedure:
			loginServiceLoginHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLoginServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLoginServiceHandler struct{}

func (UnimplementedLoginServiceHandler) Login(context.Context, *connect_go.Request[loginv1.LoginRequest]) (*connect_go.Response[loginv1.LoginResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("proto.LoginService.Login is not implemented"))
}
