// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/customError.proto

package github_com

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CustomAuthError struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Code            string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SuggestedAction string                 `protobuf:"bytes,3,opt,name=suggested_action,json=suggestedAction,proto3" json:"suggested_action,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CustomAuthError) Reset() {
	*x = CustomAuthError{}
	mi := &file_proto_customError_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomAuthError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomAuthError) ProtoMessage() {}

func (x *CustomAuthError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_customError_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomAuthError.ProtoReflect.Descriptor instead.
func (*CustomAuthError) Descriptor() ([]byte, []int) {
	return file_proto_customError_proto_rawDescGZIP(), []int{0}
}

func (x *CustomAuthError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CustomAuthError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CustomAuthError) GetSuggestedAction() string {
	if x != nil {
		return x.SuggestedAction
	}
	return ""
}

var File_proto_customError_proto protoreflect.FileDescriptor

const file_proto_customError_proto_rawDesc = "" +
	"\n" +
	"\x17proto/customError.proto\x12\aauth.v1\"j\n" +
	"\x0fCustomAuthError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x10suggested_action\x18\x03 \x01(\tR\x0fsuggestedActionB\x0fZ\r://github.comb\x06proto3"

var (
	file_proto_customError_proto_rawDescOnce sync.Once
	file_proto_customError_proto_rawDescData []byte
)

func file_proto_customError_proto_rawDescGZIP() []byte {
	file_proto_customError_proto_rawDescOnce.Do(func() {
		file_proto_customError_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_customError_proto_rawDesc), len(file_proto_customError_proto_rawDesc)))
	})
	return file_proto_customError_proto_rawDescData
}

var file_proto_customError_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_customError_proto_goTypes = []any{
	(*CustomAuthError)(nil), // 0: auth.v1.CustomAuthError
}
var file_proto_customError_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_customError_proto_init() }
func file_proto_customError_proto_init() {
	if File_proto_customError_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_customError_proto_rawDesc), len(file_proto_customError_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_customError_proto_goTypes,
		DependencyIndexes: file_proto_customError_proto_depIdxs,
		MessageInfos:      file_proto_customError_proto_msgTypes,
	}.Build()
	File_proto_customError_proto = out.File
	file_proto_customError_proto_goTypes = nil
	file_proto_customError_proto_depIdxs = nil
}
