// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/product.proto

package github_com

import (
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Descriptions   string                 `protobuf:"bytes,2,opt,name=descriptions,proto3" json:"descriptions,omitempty"`
	Qty            int32                  `protobuf:"varint,3,opt,name=qty,proto3" json:"qty,omitempty"`
	Unit           string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	CostPrice      *decimal.Decimal       `protobuf:"bytes,5,opt,name=cost_price,json=costPrice,proto3" json:"cost_price,omitempty"`
	SellPrice      *decimal.Decimal       `protobuf:"bytes,6,opt,name=sell_price,json=sellPrice,proto3" json:"sell_price,omitempty"`
	SalePrice      *decimal.Decimal       `protobuf:"bytes,7,opt,name=sale_price,json=salePrice,proto3" json:"sale_price,omitempty"`
	Productpicture string                 `protobuf:"bytes,8,opt,name=productpicture,proto3" json:"productpicture,omitempty"`
	AlertStocks    int32                  `protobuf:"varint,9,opt,name=alert_stocks,json=alertStocks,proto3" json:"alert_stocks,omitempty"`
	CriticalStocks int32                  `protobuf:"varint,10,opt,name=critical_stocks,json=criticalStocks,proto3" json:"critical_stocks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProductData) Reset() {
	*x = ProductData{}
	mi := &file_proto_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductData) ProtoMessage() {}

func (x *ProductData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductData.ProtoReflect.Descriptor instead.
func (*ProductData) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductData) GetDescriptions() string {
	if x != nil {
		return x.Descriptions
	}
	return ""
}

func (x *ProductData) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *ProductData) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ProductData) GetCostPrice() *decimal.Decimal {
	if x != nil {
		return x.CostPrice
	}
	return nil
}

func (x *ProductData) GetSellPrice() *decimal.Decimal {
	if x != nil {
		return x.SellPrice
	}
	return nil
}

func (x *ProductData) GetSalePrice() *decimal.Decimal {
	if x != nil {
		return x.SalePrice
	}
	return nil
}

func (x *ProductData) GetProductpicture() string {
	if x != nil {
		return x.Productpicture
	}
	return ""
}

func (x *ProductData) GetAlertStocks() int32 {
	if x != nil {
		return x.AlertStocks
	}
	return 0
}

func (x *ProductData) GetCriticalStocks() int32 {
	if x != nil {
		return x.CriticalStocks
	}
	return 0
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_proto_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *ProductData           `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_proto_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductResponse) GetProduct() *ProductData {
	if x != nil {
		return x.Product
	}
	return nil
}

var File_proto_product_proto protoreflect.FileDescriptor

const file_proto_product_proto_rawDesc = "" +
	"\n" +
	"\x13proto/product.proto\x12\x05proto\x1a%third_party/google/type/decimal.proto\"\xfa\x02\n" +
	"\vProductData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\fdescriptions\x18\x02 \x01(\tR\fdescriptions\x12\x10\n" +
	"\x03qty\x18\x03 \x01(\x05R\x03qty\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\x123\n" +
	"\n" +
	"cost_price\x18\x05 \x01(\v2\x14.google.type.DecimalR\tcostPrice\x123\n" +
	"\n" +
	"sell_price\x18\x06 \x01(\v2\x14.google.type.DecimalR\tsellPrice\x123\n" +
	"\n" +
	"sale_price\x18\a \x01(\v2\x14.google.type.DecimalR\tsalePrice\x12&\n" +
	"\x0eproductpicture\x18\b \x01(\tR\x0eproductpicture\x12!\n" +
	"\falert_stocks\x18\t \x01(\x05R\valertStocks\x12'\n" +
	"\x0fcritical_stocks\x18\n" +
	" \x01(\x05R\x0ecriticalStocks\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x12GetProductResponse\x12,\n" +
	"\aproduct\x18\x01 \x01(\v2\x12.proto.ProductDataR\aproduct2S\n" +
	"\x0eProductService\x12A\n" +
	"\n" +
	"GetProduct\x12\x18.proto.GetProductRequest\x1a\x19.proto.GetProductResponseB\x0fZ\r://github.comb\x06proto3"

var (
	file_proto_product_proto_rawDescOnce sync.Once
	file_proto_product_proto_rawDescData []byte
)

func file_proto_product_proto_rawDescGZIP() []byte {
	file_proto_product_proto_rawDescOnce.Do(func() {
		file_proto_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_proto_rawDesc), len(file_proto_product_proto_rawDesc)))
	})
	return file_proto_product_proto_rawDescData
}

var file_proto_product_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_product_proto_goTypes = []any{
	(*ProductData)(nil),        // 0: proto.ProductData
	(*GetProductRequest)(nil),  // 1: proto.GetProductRequest
	(*GetProductResponse)(nil), // 2: proto.GetProductResponse
	(*decimal.Decimal)(nil),    // 3: google.type.Decimal
}
var file_proto_product_proto_depIdxs = []int32{
	3, // 0: proto.ProductData.cost_price:type_name -> google.type.Decimal
	3, // 1: proto.ProductData.sell_price:type_name -> google.type.Decimal
	3, // 2: proto.ProductData.sale_price:type_name -> google.type.Decimal
	0, // 3: proto.GetProductResponse.product:type_name -> proto.ProductData
	1, // 4: proto.ProductService.GetProduct:input_type -> proto.GetProductRequest
	2, // 5: proto.ProductService.GetProduct:output_type -> proto.GetProductResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_product_proto_init() }
func file_proto_product_proto_init() {
	if File_proto_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_proto_rawDesc), len(file_proto_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_proto_goTypes,
		DependencyIndexes: file_proto_product_proto_depIdxs,
		MessageInfos:      file_proto_product_proto_msgTypes,
	}.Build()
	File_proto_product_proto = out.File
	file_proto_product_proto_goTypes = nil
	file_proto_product_proto_depIdxs = nil
}
