// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/sale.proto

package github_com

import (
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sale struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SalesAmount   *decimal.Decimal       `protobuf:"bytes,2,opt,name=sales_amount,json=salesAmount,proto3" json:"sales_amount,omitempty"`
	SalesDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=sales_date,json=salesDate,proto3" json:"sales_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sale) Reset() {
	*x = Sale{}
	mi := &file_proto_sale_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sale) ProtoMessage() {}

func (x *Sale) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sale_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sale.ProtoReflect.Descriptor instead.
func (*Sale) Descriptor() ([]byte, []int) {
	return file_proto_sale_proto_rawDescGZIP(), []int{0}
}

func (x *Sale) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Sale) GetSalesAmount() *decimal.Decimal {
	if x != nil {
		return x.SalesAmount
	}
	return nil
}

func (x *Sale) GetSalesDate() *timestamppb.Timestamp {
	if x != nil {
		return x.SalesDate
	}
	return nil
}

type GetSaleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSaleRequest) Reset() {
	*x = GetSaleRequest{}
	mi := &file_proto_sale_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSaleRequest) ProtoMessage() {}

func (x *GetSaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sale_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSaleRequest.ProtoReflect.Descriptor instead.
func (*GetSaleRequest) Descriptor() ([]byte, []int) {
	return file_proto_sale_proto_rawDescGZIP(), []int{1}
}

func (x *GetSaleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSaleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sale          *Sale                  `protobuf:"bytes,1,opt,name=sale,proto3" json:"sale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSaleResponse) Reset() {
	*x = GetSaleResponse{}
	mi := &file_proto_sale_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSaleResponse) ProtoMessage() {}

func (x *GetSaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sale_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSaleResponse.ProtoReflect.Descriptor instead.
func (*GetSaleResponse) Descriptor() ([]byte, []int) {
	return file_proto_sale_proto_rawDescGZIP(), []int{2}
}

func (x *GetSaleResponse) GetSale() *Sale {
	if x != nil {
		return x.Sale
	}
	return nil
}

var File_proto_sale_proto protoreflect.FileDescriptor

const file_proto_sale_proto_rawDesc = "" +
	"\n" +
	"\x10proto/sale.proto\x12\x05proto\x1a%third_party/google/type/decimal.proto\x1a+third_party/google/protobuf/timestamp.proto\"\x8a\x01\n" +
	"\x04Sale\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\fsales_amount\x18\x02 \x01(\v2\x14.google.type.DecimalR\vsalesAmount\x129\n" +
	"\n" +
	"sales_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tsalesDate\" \n" +
	"\x0eGetSaleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x0fGetSaleResponse\x12\x1f\n" +
	"\x04sale\x18\x01 \x01(\v2\v.proto.SaleR\x04sale2G\n" +
	"\vSaleService\x128\n" +
	"\aGetSale\x12\x15.proto.GetSaleRequest\x1a\x16.proto.GetSaleResponseB\x0fZ\r://github.comb\x06proto3"

var (
	file_proto_sale_proto_rawDescOnce sync.Once
	file_proto_sale_proto_rawDescData []byte
)

func file_proto_sale_proto_rawDescGZIP() []byte {
	file_proto_sale_proto_rawDescOnce.Do(func() {
		file_proto_sale_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sale_proto_rawDesc), len(file_proto_sale_proto_rawDesc)))
	})
	return file_proto_sale_proto_rawDescData
}

var file_proto_sale_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_sale_proto_goTypes = []any{
	(*Sale)(nil),                  // 0: proto.Sale
	(*GetSaleRequest)(nil),        // 1: proto.GetSaleRequest
	(*GetSaleResponse)(nil),       // 2: proto.GetSaleResponse
	(*decimal.Decimal)(nil),       // 3: google.type.Decimal
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_proto_sale_proto_depIdxs = []int32{
	3, // 0: proto.Sale.sales_amount:type_name -> google.type.Decimal
	4, // 1: proto.Sale.sales_date:type_name -> google.protobuf.Timestamp
	0, // 2: proto.GetSaleResponse.sale:type_name -> proto.Sale
	1, // 3: proto.SaleService.GetSale:input_type -> proto.GetSaleRequest
	2, // 4: proto.SaleService.GetSale:output_type -> proto.GetSaleResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_sale_proto_init() }
func file_proto_sale_proto_init() {
	if File_proto_sale_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sale_proto_rawDesc), len(file_proto_sale_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sale_proto_goTypes,
		DependencyIndexes: file_proto_sale_proto_depIdxs,
		MessageInfos:      file_proto_sale_proto_msgTypes,
	}.Build()
	File_proto_sale_proto = out.File
	file_proto_sale_proto_goTypes = nil
	file_proto_sale_proto_depIdxs = nil
}
