// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file salev1/sale.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file salev1/sale.proto.
 */
export const file_salev1_sale: GenFile = /*@__PURE__*/
  fileDesc("ChFzYWxldjEvc2FsZS5wcm90bxIFcHJvdG8iQQoJU2FsZXNEYXRhEgoKAmlkGAEgASgJEhQKDHNhbGVzX2Ftb3VudBgCIAEoCRISCgpzYWxlc19kYXRlGAMgASgJIhEKD0dldFNhbGVzUmVxdWVzdCIyChBHZXRTYWxlc1Jlc3BvbnNlEh4KBGRhdGEYASADKAsyEC5wcm90by5TYWxlc0RhdGEySwoMU2FsZXNTZXJ2aWNlEjsKCEdldFNhbGVzEhYucHJvdG8uR2V0U2FsZXNSZXF1ZXN0GhcucHJvdG8uR2V0U2FsZXNSZXNwb25zZUJxCgljb20ucHJvdG9CCVNhbGVQcm90b1ABWiVnb2xhbmdfZ3JwY19teXNxbC9wcm90by9zYWxldjE7c2FsZXYxogIDUFhYqgIFUHJvdG/KAgVQcm90b+ICEVByb3RvXEdQQk1ldGFkYXRh6gIFUHJvdG9iBnByb3RvMw");

/**
 * @generated from message proto.SalesData
 */
export type SalesData = Message<"proto.SalesData"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string sales_amount = 2;
   */
  salesAmount: string;

  /**
   * @generated from field: string sales_date = 3;
   */
  salesDate: string;
};

/**
 * Describes the message proto.SalesData.
 * Use `create(SalesDataSchema)` to create a new message.
 */
export const SalesDataSchema: GenMessage<SalesData> = /*@__PURE__*/
  messageDesc(file_salev1_sale, 0);

/**
 * @generated from message proto.GetSalesRequest
 */
export type GetSalesRequest = Message<"proto.GetSalesRequest"> & {
};

/**
 * Describes the message proto.GetSalesRequest.
 * Use `create(GetSalesRequestSchema)` to create a new message.
 */
export const GetSalesRequestSchema: GenMessage<GetSalesRequest> = /*@__PURE__*/
  messageDesc(file_salev1_sale, 1);

/**
 * @generated from message proto.GetSalesResponse
 */
export type GetSalesResponse = Message<"proto.GetSalesResponse"> & {
  /**
   * @generated from field: repeated proto.SalesData data = 1;
   */
  data: SalesData[];
};

/**
 * Describes the message proto.GetSalesResponse.
 * Use `create(GetSalesResponseSchema)` to create a new message.
 */
export const GetSalesResponseSchema: GenMessage<GetSalesResponse> = /*@__PURE__*/
  messageDesc(file_salev1_sale, 2);

/**
 * @generated from service proto.SalesService
 */
export const SalesService: GenService<{
  /**
   * @generated from rpc proto.SalesService.GetSales
   */
  getSales: {
    methodKind: "unary";
    input: typeof GetSalesRequestSchema;
    output: typeof GetSalesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_salev1_sale, 0);

