// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/mfav1/mfa.proto

package mfav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MfaService_MfaActivation_FullMethodName   = "/proto.MfaService/MfaActivation"
	MfaService_MfaVerification_FullMethodName = "/proto.MfaService/MfaVerification"
)

// MfaServiceClient is the client API for MfaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MfaServiceClient interface {
	MfaActivation(ctx context.Context, in *MfaActivationRequest, opts ...grpc.CallOption) (*MfaActivationResponse, error)
	MfaVerification(ctx context.Context, in *MfaVerifyRequest, opts ...grpc.CallOption) (*MfaVerifyResponse, error)
}

type mfaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMfaServiceClient(cc grpc.ClientConnInterface) MfaServiceClient {
	return &mfaServiceClient{cc}
}

func (c *mfaServiceClient) MfaActivation(ctx context.Context, in *MfaActivationRequest, opts ...grpc.CallOption) (*MfaActivationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MfaActivationResponse)
	err := c.cc.Invoke(ctx, MfaService_MfaActivation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mfaServiceClient) MfaVerification(ctx context.Context, in *MfaVerifyRequest, opts ...grpc.CallOption) (*MfaVerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MfaVerifyResponse)
	err := c.cc.Invoke(ctx, MfaService_MfaVerification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MfaServiceServer is the server API for MfaService service.
// All implementations must embed UnimplementedMfaServiceServer
// for forward compatibility.
type MfaServiceServer interface {
	MfaActivation(context.Context, *MfaActivationRequest) (*MfaActivationResponse, error)
	MfaVerification(context.Context, *MfaVerifyRequest) (*MfaVerifyResponse, error)
	mustEmbedUnimplementedMfaServiceServer()
}

// UnimplementedMfaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMfaServiceServer struct{}

func (UnimplementedMfaServiceServer) MfaActivation(context.Context, *MfaActivationRequest) (*MfaActivationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MfaActivation not implemented")
}
func (UnimplementedMfaServiceServer) MfaVerification(context.Context, *MfaVerifyRequest) (*MfaVerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MfaVerification not implemented")
}
func (UnimplementedMfaServiceServer) mustEmbedUnimplementedMfaServiceServer() {}
func (UnimplementedMfaServiceServer) testEmbeddedByValue()                    {}

// UnsafeMfaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MfaServiceServer will
// result in compilation errors.
type UnsafeMfaServiceServer interface {
	mustEmbedUnimplementedMfaServiceServer()
}

func RegisterMfaServiceServer(s grpc.ServiceRegistrar, srv MfaServiceServer) {
	// If the following call panics, it indicates UnimplementedMfaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MfaService_ServiceDesc, srv)
}

func _MfaService_MfaActivation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MfaActivationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MfaServiceServer).MfaActivation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MfaService_MfaActivation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MfaServiceServer).MfaActivation(ctx, req.(*MfaActivationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MfaService_MfaVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MfaVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MfaServiceServer).MfaVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MfaService_MfaVerification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MfaServiceServer).MfaVerification(ctx, req.(*MfaVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MfaService_ServiceDesc is the grpc.ServiceDesc for MfaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MfaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MfaService",
	HandlerType: (*MfaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MfaActivation",
			Handler:    _MfaService_MfaActivation_Handler,
		},
		{
			MethodName: "MfaVerification",
			Handler:    _MfaService_MfaVerification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mfav1/mfa.proto",
}
