// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file registerv1/register.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file registerv1/register.proto.
 */
export const file_registerv1_register: GenFile = /*@__PURE__*/
  fileDesc("ChlyZWdpc3RlcnYxL3JlZ2lzdGVyLnByb3RvEgVwcm90byIkCgxSZWdpc3RlckRhdGESFAoMdGV4dF9jb250ZW50GAEgASgJInkKD1JlZ2lzdGVyUmVxdWVzdBIRCglmaXJzdG5hbWUYASABKAkSEAoIbGFzdG5hbWUYAiABKAkSDQoFZW1haWwYAyABKAkSDgoGbW9iaWxlGAQgASgJEhAKCHVzZXJuYW1lGAUgASgJEhAKCHBhc3N3b3JkGAYgASgJIjUKEFJlZ2lzdGVyUmVzcG9uc2USIQoEZGF0YRgBIAEoCzITLnByb3RvLlJlZ2lzdGVyRGF0YTJNCg5BY2NvdW50U2VydmljZRI7CghSZWdpc3RlchIWLnByb3RvLlJlZ2lzdGVyUmVxdWVzdBoXLnByb3RvLlJlZ2lzdGVyUmVzcG9uc2VCfQoJY29tLnByb3RvQg1SZWdpc3RlclByb3RvUAFaLWdvbGFuZ19ncnBjX215c3FsL3Byb3RvL3JlZ2lzdGVydjE7cmVnaXN0ZXJ2MaICA1BYWKoCBVByb3RvygIFUHJvdG/iAhFQcm90b1xHUEJNZXRhZGF0YeoCBVByb3RvYgZwcm90bzM");

/**
 * @generated from message proto.RegisterData
 */
export type RegisterData = Message<"proto.RegisterData"> & {
  /**
   * @generated from field: string text_content = 1;
   */
  textContent: string;
};

/**
 * Describes the message proto.RegisterData.
 * Use `create(RegisterDataSchema)` to create a new message.
 */
export const RegisterDataSchema: GenMessage<RegisterData> = /*@__PURE__*/
  messageDesc(file_registerv1_register, 0);

/**
 * @generated from message proto.RegisterRequest
 */
export type RegisterRequest = Message<"proto.RegisterRequest"> & {
  /**
   * @generated from field: string firstname = 1;
   */
  firstname: string;

  /**
   * @generated from field: string lastname = 2;
   */
  lastname: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: string mobile = 4;
   */
  mobile: string;

  /**
   * @generated from field: string username = 5;
   */
  username: string;

  /**
   * @generated from field: string password = 6;
   */
  password: string;
};

/**
 * Describes the message proto.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export const RegisterRequestSchema: GenMessage<RegisterRequest> = /*@__PURE__*/
  messageDesc(file_registerv1_register, 1);

/**
 * @generated from message proto.RegisterResponse
 */
export type RegisterResponse = Message<"proto.RegisterResponse"> & {
  /**
   * @generated from field: proto.RegisterData data = 1;
   */
  data?: RegisterData;
};

/**
 * Describes the message proto.RegisterResponse.
 * Use `create(RegisterResponseSchema)` to create a new message.
 */
export const RegisterResponseSchema: GenMessage<RegisterResponse> = /*@__PURE__*/
  messageDesc(file_registerv1_register, 2);

/**
 * @generated from service proto.AccountService
 */
export const AccountService: GenService<{
  /**
   * @generated from rpc proto.AccountService.Register
   */
  register: {
    methodKind: "unary";
    input: typeof RegisterRequestSchema;
    output: typeof RegisterResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_registerv1_register, 0);

