// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file mfav1/mfa.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file mfav1/mfa.proto.
 */
export const file_mfav1_mfa: GenFile = /*@__PURE__*/
  fileDesc("Cg9tZmF2MS9tZmEucHJvdG8SBXByb3RvIjwKFE1mYUFjdGl2YXRpb25SZXF1ZXN0EgoKAmlkGAEgASgJEhgKEHR3b2ZhY3RvcmVuYWJsZWQYAiABKAgiQAoVTWZhQWN0aXZhdGlvblJlc3BvbnNlEhQKDHRleHRfY29udGVudBgBIAEoCRIRCglxcmNvZGV1cmwYAiABKAkiKwoQTWZhVmVyaWZ5UmVxdWVzdBIKCgJpZBgBIAEoCRILCgNvdHAYAiABKAkiTQoRTWZhVmVyaWZ5UmVzcG9uc2USFAoMdGV4dF9jb250ZW50GAEgASgJEhUKCHVzZXJuYW1lGAIgASgJSACIAQFCCwoJX3VzZXJuYW1lMp4BCgpNZmFTZXJ2aWNlEkoKDU1mYUFjdGl2YXRpb24SGy5wcm90by5NZmFBY3RpdmF0aW9uUmVxdWVzdBocLnByb3RvLk1mYUFjdGl2YXRpb25SZXNwb25zZRJECg9NZmFWZXJpZmljYXRpb24SFy5wcm90by5NZmFWZXJpZnlSZXF1ZXN0GhgucHJvdG8uTWZhVmVyaWZ5UmVzcG9uc2VCbgoJY29tLnByb3RvQghNZmFQcm90b1ABWiNnb2xhbmdfZ3JwY19teXNxbC9wcm90by9tZmF2MTttZmF2MaICA1BYWKoCBVByb3RvygIFUHJvdG/iAhFQcm90b1xHUEJNZXRhZGF0YeoCBVByb3RvYgZwcm90bzM");

/**
 * @generated from message proto.MfaActivationRequest
 */
export type MfaActivationRequest = Message<"proto.MfaActivationRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: bool twofactorenabled = 2;
   */
  twofactorenabled: boolean;
};

/**
 * Describes the message proto.MfaActivationRequest.
 * Use `create(MfaActivationRequestSchema)` to create a new message.
 */
export const MfaActivationRequestSchema: GenMessage<MfaActivationRequest> = /*@__PURE__*/
  messageDesc(file_mfav1_mfa, 0);

/**
 * @generated from message proto.MfaActivationResponse
 */
export type MfaActivationResponse = Message<"proto.MfaActivationResponse"> & {
  /**
   * @generated from field: string text_content = 1;
   */
  textContent: string;

  /**
   * @generated from field: string qrcodeurl = 2;
   */
  qrcodeurl: string;
};

/**
 * Describes the message proto.MfaActivationResponse.
 * Use `create(MfaActivationResponseSchema)` to create a new message.
 */
export const MfaActivationResponseSchema: GenMessage<MfaActivationResponse> = /*@__PURE__*/
  messageDesc(file_mfav1_mfa, 1);

/**
 * @generated from message proto.MfaVerifyRequest
 */
export type MfaVerifyRequest = Message<"proto.MfaVerifyRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string otp = 2;
   */
  otp: string;
};

/**
 * Describes the message proto.MfaVerifyRequest.
 * Use `create(MfaVerifyRequestSchema)` to create a new message.
 */
export const MfaVerifyRequestSchema: GenMessage<MfaVerifyRequest> = /*@__PURE__*/
  messageDesc(file_mfav1_mfa, 2);

/**
 * @generated from message proto.MfaVerifyResponse
 */
export type MfaVerifyResponse = Message<"proto.MfaVerifyResponse"> & {
  /**
   * @generated from field: string text_content = 1;
   */
  textContent: string;

  /**
   * @generated from field: optional string username = 2;
   */
  username?: string;
};

/**
 * Describes the message proto.MfaVerifyResponse.
 * Use `create(MfaVerifyResponseSchema)` to create a new message.
 */
export const MfaVerifyResponseSchema: GenMessage<MfaVerifyResponse> = /*@__PURE__*/
  messageDesc(file_mfav1_mfa, 3);

/**
 * @generated from service proto.MfaService
 */
export const MfaService: GenService<{
  /**
   * @generated from rpc proto.MfaService.MfaActivation
   */
  mfaActivation: {
    methodKind: "unary";
    input: typeof MfaActivationRequestSchema;
    output: typeof MfaActivationResponseSchema;
  },
  /**
   * @generated from rpc proto.MfaService.MfaVerification
   */
  mfaVerification: {
    methodKind: "unary";
    input: typeof MfaVerifyRequestSchema;
    output: typeof MfaVerifyResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_mfav1_mfa, 0);

