// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/uploadv1/uploadImage.proto

package uploadv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UploadPictureService_UploadProfilePicture_FullMethodName = "/proto.UploadPictureService/UploadProfilePicture"
)

// UploadPictureServiceClient is the client API for UploadPictureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UploadPictureServiceClient interface {
	UploadProfilePicture(ctx context.Context, in *UserPictureRequest, opts ...grpc.CallOption) (*UserPictureResponse, error)
}

type uploadPictureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUploadPictureServiceClient(cc grpc.ClientConnInterface) UploadPictureServiceClient {
	return &uploadPictureServiceClient{cc}
}

func (c *uploadPictureServiceClient) UploadProfilePicture(ctx context.Context, in *UserPictureRequest, opts ...grpc.CallOption) (*UserPictureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserPictureResponse)
	err := c.cc.Invoke(ctx, UploadPictureService_UploadProfilePicture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UploadPictureServiceServer is the server API for UploadPictureService service.
// All implementations must embed UnimplementedUploadPictureServiceServer
// for forward compatibility.
type UploadPictureServiceServer interface {
	UploadProfilePicture(context.Context, *UserPictureRequest) (*UserPictureResponse, error)
	mustEmbedUnimplementedUploadPictureServiceServer()
}

// UnimplementedUploadPictureServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUploadPictureServiceServer struct{}

func (UnimplementedUploadPictureServiceServer) UploadProfilePicture(context.Context, *UserPictureRequest) (*UserPictureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadProfilePicture not implemented")
}
func (UnimplementedUploadPictureServiceServer) mustEmbedUnimplementedUploadPictureServiceServer() {}
func (UnimplementedUploadPictureServiceServer) testEmbeddedByValue()                              {}

// UnsafeUploadPictureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UploadPictureServiceServer will
// result in compilation errors.
type UnsafeUploadPictureServiceServer interface {
	mustEmbedUnimplementedUploadPictureServiceServer()
}

func RegisterUploadPictureServiceServer(s grpc.ServiceRegistrar, srv UploadPictureServiceServer) {
	// If the following call panics, it indicates UnimplementedUploadPictureServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UploadPictureService_ServiceDesc, srv)
}

func _UploadPictureService_UploadProfilePicture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPictureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploadPictureServiceServer).UploadProfilePicture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UploadPictureService_UploadProfilePicture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploadPictureServiceServer).UploadProfilePicture(ctx, req.(*UserPictureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UploadPictureService_ServiceDesc is the grpc.ServiceDesc for UploadPictureService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UploadPictureService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UploadPictureService",
	HandlerType: (*UploadPictureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadProfilePicture",
			Handler:    _UploadPictureService_UploadProfilePicture_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/uploadv1/uploadImage.proto",
}
