// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/uploadv1/uploadImage.proto

package uploadv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserPictureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FileData      []byte                 `protobuf:"bytes,2,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"` // Add this to receive the file bytes
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`                 // Add this to receive the file extension/name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPictureRequest) Reset() {
	*x = UserPictureRequest{}
	mi := &file_proto_uploadv1_uploadImage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPictureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPictureRequest) ProtoMessage() {}

func (x *UserPictureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uploadv1_uploadImage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPictureRequest.ProtoReflect.Descriptor instead.
func (*UserPictureRequest) Descriptor() ([]byte, []int) {
	return file_proto_uploadv1_uploadImage_proto_rawDescGZIP(), []int{0}
}

func (x *UserPictureRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserPictureRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *UserPictureRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type UserPictureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TextContent   string                 `protobuf:"bytes,1,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	Userpicture   string                 `protobuf:"bytes,2,opt,name=userpicture,proto3" json:"userpicture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPictureResponse) Reset() {
	*x = UserPictureResponse{}
	mi := &file_proto_uploadv1_uploadImage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPictureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPictureResponse) ProtoMessage() {}

func (x *UserPictureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uploadv1_uploadImage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPictureResponse.ProtoReflect.Descriptor instead.
func (*UserPictureResponse) Descriptor() ([]byte, []int) {
	return file_proto_uploadv1_uploadImage_proto_rawDescGZIP(), []int{1}
}

func (x *UserPictureResponse) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

func (x *UserPictureResponse) GetUserpicture() string {
	if x != nil {
		return x.Userpicture
	}
	return ""
}

var File_proto_uploadv1_uploadImage_proto protoreflect.FileDescriptor

const file_proto_uploadv1_uploadImage_proto_rawDesc = "" +
	"\n" +
	" proto/uploadv1/uploadImage.proto\x12\x05proto\"]\n" +
	"\x12UserPictureRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfile_data\x18\x02 \x01(\fR\bfileData\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\"Z\n" +
	"\x13UserPictureResponse\x12!\n" +
	"\ftext_content\x18\x01 \x01(\tR\vtextContent\x12 \n" +
	"\vuserpicture\x18\x02 \x01(\tR\vuserpicture2e\n" +
	"\x14UploadPictureService\x12M\n" +
	"\x14UploadProfilePicture\x12\x19.proto.UserPictureRequest\x1a\x1a.proto.UserPictureResponseB+Z)golang_grpc_mysql/proto/uploadv1;uploadv1b\x06proto3"

var (
	file_proto_uploadv1_uploadImage_proto_rawDescOnce sync.Once
	file_proto_uploadv1_uploadImage_proto_rawDescData []byte
)

func file_proto_uploadv1_uploadImage_proto_rawDescGZIP() []byte {
	file_proto_uploadv1_uploadImage_proto_rawDescOnce.Do(func() {
		file_proto_uploadv1_uploadImage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_uploadv1_uploadImage_proto_rawDesc), len(file_proto_uploadv1_uploadImage_proto_rawDesc)))
	})
	return file_proto_uploadv1_uploadImage_proto_rawDescData
}

var file_proto_uploadv1_uploadImage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_uploadv1_uploadImage_proto_goTypes = []any{
	(*UserPictureRequest)(nil),  // 0: proto.UserPictureRequest
	(*UserPictureResponse)(nil), // 1: proto.UserPictureResponse
}
var file_proto_uploadv1_uploadImage_proto_depIdxs = []int32{
	0, // 0: proto.UploadPictureService.UploadProfilePicture:input_type -> proto.UserPictureRequest
	1, // 1: proto.UploadPictureService.UploadProfilePicture:output_type -> proto.UserPictureResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_uploadv1_uploadImage_proto_init() }
func file_proto_uploadv1_uploadImage_proto_init() {
	if File_proto_uploadv1_uploadImage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_uploadv1_uploadImage_proto_rawDesc), len(file_proto_uploadv1_uploadImage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_uploadv1_uploadImage_proto_goTypes,
		DependencyIndexes: file_proto_uploadv1_uploadImage_proto_depIdxs,
		MessageInfos:      file_proto_uploadv1_uploadImage_proto_msgTypes,
	}.Build()
	File_proto_uploadv1_uploadImage_proto = out.File
	file_proto_uploadv1_uploadImage_proto_goTypes = nil
	file_proto_uploadv1_uploadImage_proto_depIdxs = nil
}
