// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/userv1/user.proto

package userv1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	userv1 "golang_grpc_mysql/proto/userv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// UserServiceName is the fully-qualified name of the UserService service.
	UserServiceName = "proto.UserService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserServiceGetUserProcedure is the fully-qualified name of the UserService's GetUser RPC.
	UserServiceGetUserProcedure = "/proto.UserService/GetUser"
	// UserServiceGetAllUsersProcedure is the fully-qualified name of the UserService's GetAllUsers RPC.
	UserServiceGetAllUsersProcedure = "/proto.UserService/GetAllUsers"
	// UserServiceUpdateUserProfileProcedure is the fully-qualified name of the UserService's
	// UpdateUserProfile RPC.
	UserServiceUpdateUserProfileProcedure = "/proto.UserService/UpdateUserProfile"
	// UserServiceChangePasswordProcedure is the fully-qualified name of the UserService's
	// ChangePassword RPC.
	UserServiceChangePasswordProcedure = "/proto.UserService/ChangePassword"
)

// UserServiceClient is a client for the proto.UserService service.
type UserServiceClient interface {
	GetUser(context.Context, *connect_go.Request[userv1.GetUserRequest]) (*connect_go.Response[userv1.GetUserResponse], error)
	GetAllUsers(context.Context, *connect_go.Request[userv1.GetAllUsersRequest]) (*connect_go.Response[userv1.GetAllUsersResponse], error)
	UpdateUserProfile(context.Context, *connect_go.Request[userv1.UpdateUserProfileRequest]) (*connect_go.Response[userv1.UpdateUserProfileResponse], error)
	ChangePassword(context.Context, *connect_go.Request[userv1.ChangePasswordRequest]) (*connect_go.Response[userv1.ChangePasswordResponse], error)
}

// NewUserServiceClient constructs a client for the proto.UserService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) UserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &userServiceClient{
		getUser: connect_go.NewClient[userv1.GetUserRequest, userv1.GetUserResponse](
			httpClient,
			baseURL+UserServiceGetUserProcedure,
			opts...,
		),
		getAllUsers: connect_go.NewClient[userv1.GetAllUsersRequest, userv1.GetAllUsersResponse](
			httpClient,
			baseURL+UserServiceGetAllUsersProcedure,
			opts...,
		),
		updateUserProfile: connect_go.NewClient[userv1.UpdateUserProfileRequest, userv1.UpdateUserProfileResponse](
			httpClient,
			baseURL+UserServiceUpdateUserProfileProcedure,
			opts...,
		),
		changePassword: connect_go.NewClient[userv1.ChangePasswordRequest, userv1.ChangePasswordResponse](
			httpClient,
			baseURL+UserServiceChangePasswordProcedure,
			opts...,
		),
	}
}

// userServiceClient implements UserServiceClient.
type userServiceClient struct {
	getUser           *connect_go.Client[userv1.GetUserRequest, userv1.GetUserResponse]
	getAllUsers       *connect_go.Client[userv1.GetAllUsersRequest, userv1.GetAllUsersResponse]
	updateUserProfile *connect_go.Client[userv1.UpdateUserProfileRequest, userv1.UpdateUserProfileResponse]
	changePassword    *connect_go.Client[userv1.ChangePasswordRequest, userv1.ChangePasswordResponse]
}

// GetUser calls proto.UserService.GetUser.
func (c *userServiceClient) GetUser(ctx context.Context, req *connect_go.Request[userv1.GetUserRequest]) (*connect_go.Response[userv1.GetUserResponse], error) {
	return c.getUser.CallUnary(ctx, req)
}

// GetAllUsers calls proto.UserService.GetAllUsers.
func (c *userServiceClient) GetAllUsers(ctx context.Context, req *connect_go.Request[userv1.GetAllUsersRequest]) (*connect_go.Response[userv1.GetAllUsersResponse], error) {
	return c.getAllUsers.CallUnary(ctx, req)
}

// UpdateUserProfile calls proto.UserService.UpdateUserProfile.
func (c *userServiceClient) UpdateUserProfile(ctx context.Context, req *connect_go.Request[userv1.UpdateUserProfileRequest]) (*connect_go.Response[userv1.UpdateUserProfileResponse], error) {
	return c.updateUserProfile.CallUnary(ctx, req)
}

// ChangePassword calls proto.UserService.ChangePassword.
func (c *userServiceClient) ChangePassword(ctx context.Context, req *connect_go.Request[userv1.ChangePasswordRequest]) (*connect_go.Response[userv1.ChangePasswordResponse], error) {
	return c.changePassword.CallUnary(ctx, req)
}

// UserServiceHandler is an implementation of the proto.UserService service.
type UserServiceHandler interface {
	GetUser(context.Context, *connect_go.Request[userv1.GetUserRequest]) (*connect_go.Response[userv1.GetUserResponse], error)
	GetAllUsers(context.Context, *connect_go.Request[userv1.GetAllUsersRequest]) (*connect_go.Response[userv1.GetAllUsersResponse], error)
	UpdateUserProfile(context.Context, *connect_go.Request[userv1.UpdateUserProfileRequest]) (*connect_go.Response[userv1.UpdateUserProfileResponse], error)
	ChangePassword(context.Context, *connect_go.Request[userv1.ChangePasswordRequest]) (*connect_go.Response[userv1.ChangePasswordResponse], error)
}

// NewUserServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserServiceHandler(svc UserServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	userServiceGetUserHandler := connect_go.NewUnaryHandler(
		UserServiceGetUserProcedure,
		svc.GetUser,
		opts...,
	)
	userServiceGetAllUsersHandler := connect_go.NewUnaryHandler(
		UserServiceGetAllUsersProcedure,
		svc.GetAllUsers,
		opts...,
	)
	userServiceUpdateUserProfileHandler := connect_go.NewUnaryHandler(
		UserServiceUpdateUserProfileProcedure,
		svc.UpdateUserProfile,
		opts...,
	)
	userServiceChangePasswordHandler := connect_go.NewUnaryHandler(
		UserServiceChangePasswordProcedure,
		svc.ChangePassword,
		opts...,
	)
	return "/proto.UserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserServiceGetUserProcedure:
			userServiceGetUserHandler.ServeHTTP(w, r)
		case UserServiceGetAllUsersProcedure:
			userServiceGetAllUsersHandler.ServeHTTP(w, r)
		case UserServiceUpdateUserProfileProcedure:
			userServiceUpdateUserProfileHandler.ServeHTTP(w, r)
		case UserServiceChangePasswordProcedure:
			userServiceChangePasswordHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserServiceHandler struct{}

func (UnimplementedUserServiceHandler) GetUser(context.Context, *connect_go.Request[userv1.GetUserRequest]) (*connect_go.Response[userv1.GetUserResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("proto.UserService.GetUser is not implemented"))
}

func (UnimplementedUserServiceHandler) GetAllUsers(context.Context, *connect_go.Request[userv1.GetAllUsersRequest]) (*connect_go.Response[userv1.GetAllUsersResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("proto.UserService.GetAllUsers is not implemented"))
}

func (UnimplementedUserServiceHandler) UpdateUserProfile(context.Context, *connect_go.Request[userv1.UpdateUserProfileRequest]) (*connect_go.Response[userv1.UpdateUserProfileResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("proto.UserService.UpdateUserProfile is not implemented"))
}

func (UnimplementedUserServiceHandler) ChangePassword(context.Context, *connect_go.Request[userv1.ChangePasswordRequest]) (*connect_go.Response[userv1.ChangePasswordResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("proto.UserService.ChangePassword is not implemented"))
}
