// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file loginv1/login.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file loginv1/login.proto.
 */
export const file_loginv1_login: GenFile = /*@__PURE__*/
  fileDesc("ChNsb2dpbnYxL2xvZ2luLnByb3RvEgVwcm90byKSAgoJTG9naW5EYXRhEhQKDHRleHRfY29udGVudBgBIAEoCRIKCgJpZBgCIAEoCRISCgpmaXJzdF9uYW1lGAMgASgJEhEKCWxhc3RfbmFtZRgEIAEoCRINCgVlbWFpbBgFIAEoCRIOCgZtb2JpbGUYBiABKAkSEAoIdXNlcm5hbWUYByABKAkSEAoIdXNlcl9waWMYCCABKAkSEQoJaXNfYWN0aXZlGAkgASgIEhIKCmlzX2Jsb2NrZWQYCiABKAgSEgoKbWFpbF90b2tlbhgLIAEoBRIvCglxcmNvZGV1cmwYDCABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSDQoFdG9rZW4YDSABKAkiMgoMTG9naW5SZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJIi8KDUxvZ2luUmVzcG9uc2USHgoEZGF0YRgBIAEoCzIQLnByb3RvLkxvZ2luRGF0YTJCCgxMb2dpblNlcnZpY2USMgoFTG9naW4SEy5wcm90by5Mb2dpblJlcXVlc3QaFC5wcm90by5Mb2dpblJlc3BvbnNlQnQKCWNvbS5wcm90b0IKTG9naW5Qcm90b1ABWidnb2xhbmdfZ3JwY19teXNxbC9wcm90by9sb2dpbnYxO2xvZ2ludjGiAgNQWFiqAgVQcm90b8oCBVByb3Rv4gIRUHJvdG9cR1BCTWV0YWRhdGHqAgVQcm90b2IGcHJvdG8z", [file_google_protobuf_wrappers]);

/**
 * @generated from message proto.LoginData
 */
export type LoginData = Message<"proto.LoginData"> & {
  /**
   * @generated from field: string text_content = 1;
   */
  textContent: string;

  /**
   * @generated from field: string id = 2;
   */
  id: string;

  /**
   * @generated from field: string first_name = 3;
   */
  firstName: string;

  /**
   * @generated from field: string last_name = 4;
   */
  lastName: string;

  /**
   * @generated from field: string email = 5;
   */
  email: string;

  /**
   * @generated from field: string mobile = 6;
   */
  mobile: string;

  /**
   * @generated from field: string username = 7;
   */
  username: string;

  /**
   * @generated from field: string user_pic = 8;
   */
  userPic: string;

  /**
   * @generated from field: bool is_active = 9;
   */
  isActive: boolean;

  /**
   * @generated from field: bool is_blocked = 10;
   */
  isBlocked: boolean;

  /**
   * @generated from field: int32 mail_token = 11;
   */
  mailToken: number;

  /**
   * @generated from field: google.protobuf.StringValue qrcodeurl = 12;
   */
  qrcodeurl?: string;

  /**
   * @generated from field: string token = 13;
   */
  token: string;
};

/**
 * Describes the message proto.LoginData.
 * Use `create(LoginDataSchema)` to create a new message.
 */
export const LoginDataSchema: GenMessage<LoginData> = /*@__PURE__*/
  messageDesc(file_loginv1_login, 0);

/**
 * @generated from message proto.LoginRequest
 */
export type LoginRequest = Message<"proto.LoginRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message proto.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_loginv1_login, 1);

/**
 * @generated from message proto.LoginResponse
 */
export type LoginResponse = Message<"proto.LoginResponse"> & {
  /**
   * @generated from field: proto.LoginData data = 1;
   */
  data?: LoginData;
};

/**
 * Describes the message proto.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_loginv1_login, 2);

/**
 * @generated from service proto.LoginService
 */
export const LoginService: GenService<{
  /**
   * @generated from rpc proto.LoginService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_loginv1_login, 0);

