// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/productv1/product.proto

package productv1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	productv1 "golang_grpc_mysql/proto/productv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// ProductServiceName is the fully-qualified name of the ProductService service.
	ProductServiceName = "proto.ProductService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProductServiceGetProductListProcedure is the fully-qualified name of the ProductService's
	// GetProductList RPC.
	ProductServiceGetProductListProcedure = "/proto.ProductService/GetProductList"
	// ProductServiceGetProductSearchProcedure is the fully-qualified name of the ProductService's
	// GetProductSearch RPC.
	ProductServiceGetProductSearchProcedure = "/proto.ProductService/GetProductSearch"
	// ProductServiceGetProductPdfReportProcedure is the fully-qualified name of the ProductService's
	// GetProductPdfReport RPC.
	ProductServiceGetProductPdfReportProcedure = "/proto.ProductService/GetProductPdfReport"
)

// ProductServiceClient is a client for the proto.ProductService service.
type ProductServiceClient interface {
	GetProductList(context.Context, *connect_go.Request[productv1.GetProductListRequest]) (*connect_go.Response[productv1.GetProductListResponse], error)
	GetProductSearch(context.Context, *connect_go.Request[productv1.GetProductSearchRequest]) (*connect_go.Response[productv1.GetProductSearchResponse], error)
	GetProductPdfReport(context.Context, *connect_go.Request[productv1.GetProductReportRequest]) (*connect_go.Response[productv1.GetProductReportResponse], error)
}

// NewProductServiceClient constructs a client for the proto.ProductService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProductServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) ProductServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &productServiceClient{
		getProductList: connect_go.NewClient[productv1.GetProductListRequest, productv1.GetProductListResponse](
			httpClient,
			baseURL+ProductServiceGetProductListProcedure,
			opts...,
		),
		getProductSearch: connect_go.NewClient[productv1.GetProductSearchRequest, productv1.GetProductSearchResponse](
			httpClient,
			baseURL+ProductServiceGetProductSearchProcedure,
			opts...,
		),
		getProductPdfReport: connect_go.NewClient[productv1.GetProductReportRequest, productv1.GetProductReportResponse](
			httpClient,
			baseURL+ProductServiceGetProductPdfReportProcedure,
			opts...,
		),
	}
}

// productServiceClient implements ProductServiceClient.
type productServiceClient struct {
	getProductList      *connect_go.Client[productv1.GetProductListRequest, productv1.GetProductListResponse]
	getProductSearch    *connect_go.Client[productv1.GetProductSearchRequest, productv1.GetProductSearchResponse]
	getProductPdfReport *connect_go.Client[productv1.GetProductReportRequest, productv1.GetProductReportResponse]
}

// GetProductList calls proto.ProductService.GetProductList.
func (c *productServiceClient) GetProductList(ctx context.Context, req *connect_go.Request[productv1.GetProductListRequest]) (*connect_go.Response[productv1.GetProductListResponse], error) {
	return c.getProductList.CallUnary(ctx, req)
}

// GetProductSearch calls proto.ProductService.GetProductSearch.
func (c *productServiceClient) GetProductSearch(ctx context.Context, req *connect_go.Request[productv1.GetProductSearchRequest]) (*connect_go.Response[productv1.GetProductSearchResponse], error) {
	return c.getProductSearch.CallUnary(ctx, req)
}

// GetProductPdfReport calls proto.ProductService.GetProductPdfReport.
func (c *productServiceClient) GetProductPdfReport(ctx context.Context, req *connect_go.Request[productv1.GetProductReportRequest]) (*connect_go.Response[productv1.GetProductReportResponse], error) {
	return c.getProductPdfReport.CallUnary(ctx, req)
}

// ProductServiceHandler is an implementation of the proto.ProductService service.
type ProductServiceHandler interface {
	GetProductList(context.Context, *connect_go.Request[productv1.GetProductListRequest]) (*connect_go.Response[productv1.GetProductListResponse], error)
	GetProductSearch(context.Context, *connect_go.Request[productv1.GetProductSearchRequest]) (*connect_go.Response[productv1.GetProductSearchResponse], error)
	GetProductPdfReport(context.Context, *connect_go.Request[productv1.GetProductReportRequest]) (*connect_go.Response[productv1.GetProductReportResponse], error)
}

// NewProductServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProductServiceHandler(svc ProductServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	productServiceGetProductListHandler := connect_go.NewUnaryHandler(
		ProductServiceGetProductListProcedure,
		svc.GetProductList,
		opts...,
	)
	productServiceGetProductSearchHandler := connect_go.NewUnaryHandler(
		ProductServiceGetProductSearchProcedure,
		svc.GetProductSearch,
		opts...,
	)
	productServiceGetProductPdfReportHandler := connect_go.NewUnaryHandler(
		ProductServiceGetProductPdfReportProcedure,
		svc.GetProductPdfReport,
		opts...,
	)
	return "/proto.ProductService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProductServiceGetProductListProcedure:
			productServiceGetProductListHandler.ServeHTTP(w, r)
		case ProductServiceGetProductSearchProcedure:
			productServiceGetProductSearchHandler.ServeHTTP(w, r)
		case ProductServiceGetProductPdfReportProcedure:
			productServiceGetProductPdfReportHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProductServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProductServiceHandler struct{}

func (UnimplementedProductServiceHandler) GetProductList(context.Context, *connect_go.Request[productv1.GetProductListRequest]) (*connect_go.Response[productv1.GetProductListResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("proto.ProductService.GetProductList is not implemented"))
}

func (UnimplementedProductServiceHandler) GetProductSearch(context.Context, *connect_go.Request[productv1.GetProductSearchRequest]) (*connect_go.Response[productv1.GetProductSearchResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("proto.ProductService.GetProductSearch is not implemented"))
}

func (UnimplementedProductServiceHandler) GetProductPdfReport(context.Context, *connect_go.Request[productv1.GetProductReportRequest]) (*connect_go.Response[productv1.GetProductReportResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("proto.ProductService.GetProductPdfReport is not implemented"))
}
