// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file uploadv1/uploadImage.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file uploadv1/uploadImage.proto.
 */
export const file_uploadv1_uploadImage: GenFile = /*@__PURE__*/
  fileDesc("Chp1cGxvYWR2MS91cGxvYWRJbWFnZS5wcm90bxIFcHJvdG8iRQoSVXNlclBpY3R1cmVSZXF1ZXN0EgoKAmlkGAEgASgJEhEKCWZpbGVfZGF0YRgCIAEoDBIQCghmaWxlbmFtZRgDIAEoCSJAChNVc2VyUGljdHVyZVJlc3BvbnNlEhQKDHRleHRfY29udGVudBgBIAEoCRITCgt1c2VycGljdHVyZRgCIAEoCTJlChRVcGxvYWRQaWN0dXJlU2VydmljZRJNChRVcGxvYWRQcm9maWxlUGljdHVyZRIZLnByb3RvLlVzZXJQaWN0dXJlUmVxdWVzdBoaLnByb3RvLlVzZXJQaWN0dXJlUmVzcG9uc2VCfAoJY29tLnByb3RvQhBVcGxvYWRJbWFnZVByb3RvUAFaKWdvbGFuZ19ncnBjX215c3FsL3Byb3RvL3VwbG9hZHYxO3VwbG9hZHYxogIDUFhYqgIFUHJvdG/KAgVQcm90b+ICEVByb3RvXEdQQk1ldGFkYXRh6gIFUHJvdG9iBnByb3RvMw");

/**
 * @generated from message proto.UserPictureRequest
 */
export type UserPictureRequest = Message<"proto.UserPictureRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Add this to receive the file bytes
   *
   * @generated from field: bytes file_data = 2;
   */
  fileData: Uint8Array;

  /**
   * Add this to receive the file extension/name  
   *
   * @generated from field: string filename = 3;
   */
  filename: string;
};

/**
 * Describes the message proto.UserPictureRequest.
 * Use `create(UserPictureRequestSchema)` to create a new message.
 */
export const UserPictureRequestSchema: GenMessage<UserPictureRequest> = /*@__PURE__*/
  messageDesc(file_uploadv1_uploadImage, 0);

/**
 * @generated from message proto.UserPictureResponse
 */
export type UserPictureResponse = Message<"proto.UserPictureResponse"> & {
  /**
   * @generated from field: string text_content = 1;
   */
  textContent: string;

  /**
   * @generated from field: string userpicture = 2;
   */
  userpicture: string;
};

/**
 * Describes the message proto.UserPictureResponse.
 * Use `create(UserPictureResponseSchema)` to create a new message.
 */
export const UserPictureResponseSchema: GenMessage<UserPictureResponse> = /*@__PURE__*/
  messageDesc(file_uploadv1_uploadImage, 1);

/**
 * @generated from service proto.UploadPictureService
 */
export const UploadPictureService: GenService<{
  /**
   * @generated from rpc proto.UploadPictureService.UploadProfilePicture
   */
  uploadProfilePicture: {
    methodKind: "unary";
    input: typeof UserPictureRequestSchema;
    output: typeof UserPictureResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_uploadv1_uploadImage, 0);

