// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/registerv1/register.proto

package registerv1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	registerv1 "golang_grpc_mysql/proto/registerv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// AccountServiceName is the fully-qualified name of the AccountService service.
	AccountServiceName = "proto.AccountService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AccountServiceRegisterProcedure is the fully-qualified name of the AccountService's Register RPC.
	AccountServiceRegisterProcedure = "/proto.AccountService/Register"
)

// AccountServiceClient is a client for the proto.AccountService service.
type AccountServiceClient interface {
	Register(context.Context, *connect_go.Request[registerv1.RegisterRequest]) (*connect_go.Response[registerv1.RegisterResponse], error)
}

// NewAccountServiceClient constructs a client for the proto.AccountService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAccountServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) AccountServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &accountServiceClient{
		register: connect_go.NewClient[registerv1.RegisterRequest, registerv1.RegisterResponse](
			httpClient,
			baseURL+AccountServiceRegisterProcedure,
			opts...,
		),
	}
}

// accountServiceClient implements AccountServiceClient.
type accountServiceClient struct {
	register *connect_go.Client[registerv1.RegisterRequest, registerv1.RegisterResponse]
}

// Register calls proto.AccountService.Register.
func (c *accountServiceClient) Register(ctx context.Context, req *connect_go.Request[registerv1.RegisterRequest]) (*connect_go.Response[registerv1.RegisterResponse], error) {
	return c.register.CallUnary(ctx, req)
}

// AccountServiceHandler is an implementation of the proto.AccountService service.
type AccountServiceHandler interface {
	Register(context.Context, *connect_go.Request[registerv1.RegisterRequest]) (*connect_go.Response[registerv1.RegisterResponse], error)
}

// NewAccountServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAccountServiceHandler(svc AccountServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	accountServiceRegisterHandler := connect_go.NewUnaryHandler(
		AccountServiceRegisterProcedure,
		svc.Register,
		opts...,
	)
	return "/proto.AccountService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AccountServiceRegisterProcedure:
			accountServiceRegisterHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAccountServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAccountServiceHandler struct{}

func (UnimplementedAccountServiceHandler) Register(context.Context, *connect_go.Request[registerv1.RegisterRequest]) (*connect_go.Response[registerv1.RegisterResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("proto.AccountService.Register is not implemented"))
}
