// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/userv1/user.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Mobile        string                 `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Username      string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	UserPic       string                 `protobuf:"bytes,7,opt,name=user_pic,json=userPic,proto3" json:"user_pic,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsBlocked     bool                   `protobuf:"varint,9,opt,name=is_blocked,json=isBlocked,proto3" json:"is_blocked,omitempty"`
	MailToken     string                 `protobuf:"bytes,10,opt,name=mail_token,json=mailToken,proto3" json:"mail_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_proto_userv1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userv1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_proto_userv1_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserProfile) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserProfile) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfile) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserProfile) GetUserPic() string {
	if x != nil {
		return x.UserPic
	}
	return ""
}

func (x *UserProfile) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UserProfile) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

func (x *UserProfile) GetMailToken() string {
	if x != nil {
		return x.MailToken
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_userv1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userv1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_userv1_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserProfile           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_proto_userv1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userv1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_userv1_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserResponse) GetUser() *UserProfile {
	if x != nil {
		return x.User
	}
	return nil
}

type GetAllUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersRequest) Reset() {
	*x = GetAllUsersRequest{}
	mi := &file_proto_userv1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersRequest) ProtoMessage() {}

func (x *GetAllUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userv1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersRequest.ProtoReflect.Descriptor instead.
func (*GetAllUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_userv1_user_proto_rawDescGZIP(), []int{3}
}

type GetAllUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserProfile         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersResponse) Reset() {
	*x = GetAllUsersResponse{}
	mi := &file_proto_userv1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersResponse) ProtoMessage() {}

func (x *GetAllUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userv1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersResponse.ProtoReflect.Descriptor instead.
func (*GetAllUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_userv1_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllUsersResponse) GetUsers() []*UserProfile {
	if x != nil {
		return x.Users
	}
	return nil
}

type UpdateUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Firstname     string                 `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname      string                 `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Mobile        string                 `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileRequest) Reset() {
	*x = UpdateUserProfileRequest{}
	mi := &file_proto_userv1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileRequest) ProtoMessage() {}

func (x *UpdateUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userv1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_userv1_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

type UpdateUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TextContent   string                 `protobuf:"bytes,1,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileResponse) Reset() {
	*x = UpdateUserProfileResponse{}
	mi := &file_proto_userv1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileResponse) ProtoMessage() {}

func (x *UpdateUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userv1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_userv1_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserProfileResponse) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

type ChangePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_proto_userv1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userv1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_userv1_user_proto_rawDescGZIP(), []int{7}
}

func (x *ChangePasswordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangePasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ChangePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TextContent   string                 `protobuf:"bytes,1,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_proto_userv1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userv1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_proto_userv1_user_proto_rawDescGZIP(), []int{8}
}

func (x *ChangePasswordResponse) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

var File_proto_userv1_user_proto protoreflect.FileDescriptor

const file_proto_userv1_user_proto_rawDesc = "" +
	"\n" +
	"\x17proto/userv1/user.proto\x12\x05proto\"\x99\x02\n" +
	"\vUserProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x16\n" +
	"\x06mobile\x18\x05 \x01(\tR\x06mobile\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12\x19\n" +
	"\buser_pic\x18\a \x01(\tR\auserPic\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"is_blocked\x18\t \x01(\bR\tisBlocked\x12\x1d\n" +
	"\n" +
	"mail_token\x18\n" +
	" \x01(\tR\tmailToken\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x0fGetUserResponse\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.proto.UserProfileR\x04user\"\x14\n" +
	"\x12GetAllUsersRequest\"?\n" +
	"\x13GetAllUsersResponse\x12(\n" +
	"\x05users\x18\x01 \x03(\v2\x12.proto.UserProfileR\x05users\"|\n" +
	"\x18UpdateUserProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tfirstname\x18\x02 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x03 \x01(\tR\blastname\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\tR\x06mobile\">\n" +
	"\x19UpdateUserProfileResponse\x12!\n" +
	"\ftext_content\x18\x01 \x01(\tR\vtextContent\"C\n" +
	"\x15ChangePasswordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\";\n" +
	"\x16ChangePasswordResponse\x12!\n" +
	"\ftext_content\x18\x01 \x01(\tR\vtextContent2\xb4\x02\n" +
	"\vUserService\x128\n" +
	"\aGetUser\x12\x15.proto.GetUserRequest\x1a\x16.proto.GetUserResponse\x12D\n" +
	"\vGetAllUsers\x12\x19.proto.GetAllUsersRequest\x1a\x1a.proto.GetAllUsersResponse\x12V\n" +
	"\x11UpdateUserProfile\x12\x1f.proto.UpdateUserProfileRequest\x1a .proto.UpdateUserProfileResponse\x12M\n" +
	"\x0eChangePassword\x12\x1c.proto.ChangePasswordRequest\x1a\x1d.proto.ChangePasswordResponseB'Z%golang_grpc_mysql/proto/userv1;userv1b\x06proto3"

var (
	file_proto_userv1_user_proto_rawDescOnce sync.Once
	file_proto_userv1_user_proto_rawDescData []byte
)

func file_proto_userv1_user_proto_rawDescGZIP() []byte {
	file_proto_userv1_user_proto_rawDescOnce.Do(func() {
		file_proto_userv1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_userv1_user_proto_rawDesc), len(file_proto_userv1_user_proto_rawDesc)))
	})
	return file_proto_userv1_user_proto_rawDescData
}

var file_proto_userv1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_userv1_user_proto_goTypes = []any{
	(*UserProfile)(nil),               // 0: proto.UserProfile
	(*GetUserRequest)(nil),            // 1: proto.GetUserRequest
	(*GetUserResponse)(nil),           // 2: proto.GetUserResponse
	(*GetAllUsersRequest)(nil),        // 3: proto.GetAllUsersRequest
	(*GetAllUsersResponse)(nil),       // 4: proto.GetAllUsersResponse
	(*UpdateUserProfileRequest)(nil),  // 5: proto.UpdateUserProfileRequest
	(*UpdateUserProfileResponse)(nil), // 6: proto.UpdateUserProfileResponse
	(*ChangePasswordRequest)(nil),     // 7: proto.ChangePasswordRequest
	(*ChangePasswordResponse)(nil),    // 8: proto.ChangePasswordResponse
}
var file_proto_userv1_user_proto_depIdxs = []int32{
	0, // 0: proto.GetUserResponse.user:type_name -> proto.UserProfile
	0, // 1: proto.GetAllUsersResponse.users:type_name -> proto.UserProfile
	1, // 2: proto.UserService.GetUser:input_type -> proto.GetUserRequest
	3, // 3: proto.UserService.GetAllUsers:input_type -> proto.GetAllUsersRequest
	5, // 4: proto.UserService.UpdateUserProfile:input_type -> proto.UpdateUserProfileRequest
	7, // 5: proto.UserService.ChangePassword:input_type -> proto.ChangePasswordRequest
	2, // 6: proto.UserService.GetUser:output_type -> proto.GetUserResponse
	4, // 7: proto.UserService.GetAllUsers:output_type -> proto.GetAllUsersResponse
	6, // 8: proto.UserService.UpdateUserProfile:output_type -> proto.UpdateUserProfileResponse
	8, // 9: proto.UserService.ChangePassword:output_type -> proto.ChangePasswordResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_userv1_user_proto_init() }
func file_proto_userv1_user_proto_init() {
	if File_proto_userv1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_userv1_user_proto_rawDesc), len(file_proto_userv1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_userv1_user_proto_goTypes,
		DependencyIndexes: file_proto_userv1_user_proto_depIdxs,
		MessageInfos:      file_proto_userv1_user_proto_msgTypes,
	}.Build()
	File_proto_userv1_user_proto = out.File
	file_proto_userv1_user_proto_goTypes = nil
	file_proto_userv1_user_proto_depIdxs = nil
}
