// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file productv1/product.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file productv1/product.proto.
 */
export const file_productv1_product: GenFile = /*@__PURE__*/
  fileDesc("Chdwcm9kdWN0djEvcHJvZHVjdC5wcm90bxIFcHJvdG8iiwEKC1Byb2R1Y3REYXRhEgoKAmlkGAEgASgJEhQKDGRlc2NyaXB0aW9ucxgCIAEoCRILCgNxdHkYAyABKAkSDAoEdW5pdBgEIAEoCRIXCg9wcm9kdWN0X3BpY3R1cmUYBSABKAkSEgoKY29zdF9wcmljZRgGIAEoCRISCgpzZWxsX3ByaWNlGAcgASgJIiUKFUdldFByb2R1Y3RMaXN0UmVxdWVzdBIMCgRwYWdlGAEgASgDIngKFkdldFByb2R1Y3RMaXN0UmVzcG9uc2USDAoEcGFnZRgBIAEoAxITCgt0b3RhbF9wYWdlcxgCIAEoAxIVCg10b3RhbF9yZWNvcmRzGAMgASgDEiQKCHByb2R1Y3RzGAQgAygLMhIucHJvdG8uUHJvZHVjdERhdGEiOAoXR2V0UHJvZHVjdFNlYXJjaFJlcXVlc3QSDAoEcGFnZRgBIAEoAxIPCgdrZXl3b3JkGAIgASgJInoKGEdldFByb2R1Y3RTZWFyY2hSZXNwb25zZRIMCgRwYWdlGAEgASgDEhMKC3RvdGFsX3BhZ2VzGAIgASgDEhUKDXRvdGFsX3JlY29yZHMYAyABKAMSJAoIcHJvZHVjdHMYBCADKAsyEi5wcm90by5Qcm9kdWN0RGF0YSIZChdHZXRQcm9kdWN0UmVwb3J0UmVxdWVzdCJAChhHZXRQcm9kdWN0UmVwb3J0UmVzcG9uc2USJAoIcHJvZHVjdHMYASADKAsyEi5wcm90by5Qcm9kdWN0RGF0YTKMAgoOUHJvZHVjdFNlcnZpY2USTQoOR2V0UHJvZHVjdExpc3QSHC5wcm90by5HZXRQcm9kdWN0TGlzdFJlcXVlc3QaHS5wcm90by5HZXRQcm9kdWN0TGlzdFJlc3BvbnNlElMKEEdldFByb2R1Y3RTZWFyY2gSHi5wcm90by5HZXRQcm9kdWN0U2VhcmNoUmVxdWVzdBofLnByb3RvLkdldFByb2R1Y3RTZWFyY2hSZXNwb25zZRJWChNHZXRQcm9kdWN0UGRmUmVwb3J0Eh4ucHJvdG8uR2V0UHJvZHVjdFJlcG9ydFJlcXVlc3QaHy5wcm90by5HZXRQcm9kdWN0UmVwb3J0UmVzcG9uc2VCegoJY29tLnByb3RvQgxQcm9kdWN0UHJvdG9QAVorZ29sYW5nX2dycGNfbXlzcWwvcHJvdG8vcHJvZHVjdHYxO3Byb2R1Y3R2MaICA1BYWKoCBVByb3RvygIFUHJvdG/iAhFQcm90b1xHUEJNZXRhZGF0YeoCBVByb3RvYgZwcm90bzM");

/**
 * @generated from message proto.ProductData
 */
export type ProductData = Message<"proto.ProductData"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string descriptions = 2;
   */
  descriptions: string;

  /**
   * @generated from field: string qty = 3;
   */
  qty: string;

  /**
   * @generated from field: string unit = 4;
   */
  unit: string;

  /**
   * @generated from field: string product_picture = 5;
   */
  productPicture: string;

  /**
   * @generated from field: string cost_price = 6;
   */
  costPrice: string;

  /**
   * @generated from field: string sell_price = 7;
   */
  sellPrice: string;
};

/**
 * Describes the message proto.ProductData.
 * Use `create(ProductDataSchema)` to create a new message.
 */
export const ProductDataSchema: GenMessage<ProductData> = /*@__PURE__*/
  messageDesc(file_productv1_product, 0);

/**
 * @generated from message proto.GetProductListRequest
 */
export type GetProductListRequest = Message<"proto.GetProductListRequest"> & {
  /**
   * @generated from field: int64 page = 1;
   */
  page: bigint;
};

/**
 * Describes the message proto.GetProductListRequest.
 * Use `create(GetProductListRequestSchema)` to create a new message.
 */
export const GetProductListRequestSchema: GenMessage<GetProductListRequest> = /*@__PURE__*/
  messageDesc(file_productv1_product, 1);

/**
 * @generated from message proto.GetProductListResponse
 */
export type GetProductListResponse = Message<"proto.GetProductListResponse"> & {
  /**
   * @generated from field: int64 page = 1;
   */
  page: bigint;

  /**
   * @generated from field: int64 total_pages = 2;
   */
  totalPages: bigint;

  /**
   * @generated from field: int64 total_records = 3;
   */
  totalRecords: bigint;

  /**
   * @generated from field: repeated proto.ProductData products = 4;
   */
  products: ProductData[];
};

/**
 * Describes the message proto.GetProductListResponse.
 * Use `create(GetProductListResponseSchema)` to create a new message.
 */
export const GetProductListResponseSchema: GenMessage<GetProductListResponse> = /*@__PURE__*/
  messageDesc(file_productv1_product, 2);

/**
 * @generated from message proto.GetProductSearchRequest
 */
export type GetProductSearchRequest = Message<"proto.GetProductSearchRequest"> & {
  /**
   * @generated from field: int64 page = 1;
   */
  page: bigint;

  /**
   * @generated from field: string keyword = 2;
   */
  keyword: string;
};

/**
 * Describes the message proto.GetProductSearchRequest.
 * Use `create(GetProductSearchRequestSchema)` to create a new message.
 */
export const GetProductSearchRequestSchema: GenMessage<GetProductSearchRequest> = /*@__PURE__*/
  messageDesc(file_productv1_product, 3);

/**
 * @generated from message proto.GetProductSearchResponse
 */
export type GetProductSearchResponse = Message<"proto.GetProductSearchResponse"> & {
  /**
   * @generated from field: int64 page = 1;
   */
  page: bigint;

  /**
   * @generated from field: int64 total_pages = 2;
   */
  totalPages: bigint;

  /**
   * @generated from field: int64 total_records = 3;
   */
  totalRecords: bigint;

  /**
   * @generated from field: repeated proto.ProductData products = 4;
   */
  products: ProductData[];
};

/**
 * Describes the message proto.GetProductSearchResponse.
 * Use `create(GetProductSearchResponseSchema)` to create a new message.
 */
export const GetProductSearchResponseSchema: GenMessage<GetProductSearchResponse> = /*@__PURE__*/
  messageDesc(file_productv1_product, 4);

/**
 * @generated from message proto.GetProductReportRequest
 */
export type GetProductReportRequest = Message<"proto.GetProductReportRequest"> & {
};

/**
 * Describes the message proto.GetProductReportRequest.
 * Use `create(GetProductReportRequestSchema)` to create a new message.
 */
export const GetProductReportRequestSchema: GenMessage<GetProductReportRequest> = /*@__PURE__*/
  messageDesc(file_productv1_product, 5);

/**
 * @generated from message proto.GetProductReportResponse
 */
export type GetProductReportResponse = Message<"proto.GetProductReportResponse"> & {
  /**
   * @generated from field: repeated proto.ProductData products = 1;
   */
  products: ProductData[];
};

/**
 * Describes the message proto.GetProductReportResponse.
 * Use `create(GetProductReportResponseSchema)` to create a new message.
 */
export const GetProductReportResponseSchema: GenMessage<GetProductReportResponse> = /*@__PURE__*/
  messageDesc(file_productv1_product, 6);

/**
 * @generated from service proto.ProductService
 */
export const ProductService: GenService<{
  /**
   * @generated from rpc proto.ProductService.GetProductList
   */
  getProductList: {
    methodKind: "unary";
    input: typeof GetProductListRequestSchema;
    output: typeof GetProductListResponseSchema;
  },
  /**
   * @generated from rpc proto.ProductService.GetProductSearch
   */
  getProductSearch: {
    methodKind: "unary";
    input: typeof GetProductSearchRequestSchema;
    output: typeof GetProductSearchResponseSchema;
  },
  /**
   * @generated from rpc proto.ProductService.GetProductPdfReport
   */
  getProductPdfReport: {
    methodKind: "unary";
    input: typeof GetProductReportRequestSchema;
    output: typeof GetProductReportResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_productv1_product, 0);

