// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/productv1/product.proto

package productv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Descriptions   string                 `protobuf:"bytes,2,opt,name=descriptions,proto3" json:"descriptions,omitempty"`
	Qty            string                 `protobuf:"bytes,3,opt,name=qty,proto3" json:"qty,omitempty"`
	Unit           string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	ProductPicture string                 `protobuf:"bytes,5,opt,name=product_picture,json=productPicture,proto3" json:"product_picture,omitempty"`
	CostPrice      string                 `protobuf:"bytes,6,opt,name=cost_price,json=costPrice,proto3" json:"cost_price,omitempty"`
	SellPrice      string                 `protobuf:"bytes,7,opt,name=sell_price,json=sellPrice,proto3" json:"sell_price,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProductData) Reset() {
	*x = ProductData{}
	mi := &file_proto_productv1_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductData) ProtoMessage() {}

func (x *ProductData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_productv1_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductData.ProtoReflect.Descriptor instead.
func (*ProductData) Descriptor() ([]byte, []int) {
	return file_proto_productv1_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductData) GetDescriptions() string {
	if x != nil {
		return x.Descriptions
	}
	return ""
}

func (x *ProductData) GetQty() string {
	if x != nil {
		return x.Qty
	}
	return ""
}

func (x *ProductData) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ProductData) GetProductPicture() string {
	if x != nil {
		return x.ProductPicture
	}
	return ""
}

func (x *ProductData) GetCostPrice() string {
	if x != nil {
		return x.CostPrice
	}
	return ""
}

func (x *ProductData) GetSellPrice() string {
	if x != nil {
		return x.SellPrice
	}
	return ""
}

type GetProductListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductListRequest) Reset() {
	*x = GetProductListRequest{}
	mi := &file_proto_productv1_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductListRequest) ProtoMessage() {}

func (x *GetProductListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_productv1_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductListRequest.ProtoReflect.Descriptor instead.
func (*GetProductListRequest) Descriptor() ([]byte, []int) {
	return file_proto_productv1_product_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetProductListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	TotalPages    int64                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	TotalRecords  int64                  `protobuf:"varint,3,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`
	Products      []*ProductData         `protobuf:"bytes,4,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductListResponse) Reset() {
	*x = GetProductListResponse{}
	mi := &file_proto_productv1_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductListResponse) ProtoMessage() {}

func (x *GetProductListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_productv1_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductListResponse.ProtoReflect.Descriptor instead.
func (*GetProductListResponse) Descriptor() ([]byte, []int) {
	return file_proto_productv1_product_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductListResponse) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetProductListResponse) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetProductListResponse) GetTotalRecords() int64 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

func (x *GetProductListResponse) GetProducts() []*ProductData {
	if x != nil {
		return x.Products
	}
	return nil
}

type GetProductSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductSearchRequest) Reset() {
	*x = GetProductSearchRequest{}
	mi := &file_proto_productv1_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductSearchRequest) ProtoMessage() {}

func (x *GetProductSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_productv1_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductSearchRequest.ProtoReflect.Descriptor instead.
func (*GetProductSearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_productv1_product_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductSearchRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetProductSearchRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type GetProductSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	TotalPages    int64                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	TotalRecords  int64                  `protobuf:"varint,3,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`
	Products      []*ProductData         `protobuf:"bytes,4,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductSearchResponse) Reset() {
	*x = GetProductSearchResponse{}
	mi := &file_proto_productv1_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductSearchResponse) ProtoMessage() {}

func (x *GetProductSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_productv1_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductSearchResponse.ProtoReflect.Descriptor instead.
func (*GetProductSearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_productv1_product_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductSearchResponse) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetProductSearchResponse) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetProductSearchResponse) GetTotalRecords() int64 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

func (x *GetProductSearchResponse) GetProducts() []*ProductData {
	if x != nil {
		return x.Products
	}
	return nil
}

type GetProductReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductReportRequest) Reset() {
	*x = GetProductReportRequest{}
	mi := &file_proto_productv1_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductReportRequest) ProtoMessage() {}

func (x *GetProductReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_productv1_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductReportRequest.ProtoReflect.Descriptor instead.
func (*GetProductReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_productv1_product_proto_rawDescGZIP(), []int{5}
}

type GetProductReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductData         `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductReportResponse) Reset() {
	*x = GetProductReportResponse{}
	mi := &file_proto_productv1_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductReportResponse) ProtoMessage() {}

func (x *GetProductReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_productv1_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductReportResponse.ProtoReflect.Descriptor instead.
func (*GetProductReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_productv1_product_proto_rawDescGZIP(), []int{6}
}

func (x *GetProductReportResponse) GetProducts() []*ProductData {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_proto_productv1_product_proto protoreflect.FileDescriptor

const file_proto_productv1_product_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/productv1/product.proto\x12\x05proto\"\xce\x01\n" +
	"\vProductData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\fdescriptions\x18\x02 \x01(\tR\fdescriptions\x12\x10\n" +
	"\x03qty\x18\x03 \x01(\tR\x03qty\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\x12'\n" +
	"\x0fproduct_picture\x18\x05 \x01(\tR\x0eproductPicture\x12\x1d\n" +
	"\n" +
	"cost_price\x18\x06 \x01(\tR\tcostPrice\x12\x1d\n" +
	"\n" +
	"sell_price\x18\a \x01(\tR\tsellPrice\"+\n" +
	"\x15GetProductListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\"\xa2\x01\n" +
	"\x16GetProductListResponse\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x03R\n" +
	"totalPages\x12#\n" +
	"\rtotal_records\x18\x03 \x01(\x03R\ftotalRecords\x12.\n" +
	"\bproducts\x18\x04 \x03(\v2\x12.proto.ProductDataR\bproducts\"G\n" +
	"\x17GetProductSearchRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\"\xa4\x01\n" +
	"\x18GetProductSearchResponse\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x03R\n" +
	"totalPages\x12#\n" +
	"\rtotal_records\x18\x03 \x01(\x03R\ftotalRecords\x12.\n" +
	"\bproducts\x18\x04 \x03(\v2\x12.proto.ProductDataR\bproducts\"\x19\n" +
	"\x17GetProductReportRequest\"J\n" +
	"\x18GetProductReportResponse\x12.\n" +
	"\bproducts\x18\x01 \x03(\v2\x12.proto.ProductDataR\bproducts2\x8c\x02\n" +
	"\x0eProductService\x12M\n" +
	"\x0eGetProductList\x12\x1c.proto.GetProductListRequest\x1a\x1d.proto.GetProductListResponse\x12S\n" +
	"\x10GetProductSearch\x12\x1e.proto.GetProductSearchRequest\x1a\x1f.proto.GetProductSearchResponse\x12V\n" +
	"\x13GetProductPdfReport\x12\x1e.proto.GetProductReportRequest\x1a\x1f.proto.GetProductReportResponseB-Z+golang_grpc_mysql/proto/productv1;productv1b\x06proto3"

var (
	file_proto_productv1_product_proto_rawDescOnce sync.Once
	file_proto_productv1_product_proto_rawDescData []byte
)

func file_proto_productv1_product_proto_rawDescGZIP() []byte {
	file_proto_productv1_product_proto_rawDescOnce.Do(func() {
		file_proto_productv1_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_productv1_product_proto_rawDesc), len(file_proto_productv1_product_proto_rawDesc)))
	})
	return file_proto_productv1_product_proto_rawDescData
}

var file_proto_productv1_product_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_productv1_product_proto_goTypes = []any{
	(*ProductData)(nil),              // 0: proto.ProductData
	(*GetProductListRequest)(nil),    // 1: proto.GetProductListRequest
	(*GetProductListResponse)(nil),   // 2: proto.GetProductListResponse
	(*GetProductSearchRequest)(nil),  // 3: proto.GetProductSearchRequest
	(*GetProductSearchResponse)(nil), // 4: proto.GetProductSearchResponse
	(*GetProductReportRequest)(nil),  // 5: proto.GetProductReportRequest
	(*GetProductReportResponse)(nil), // 6: proto.GetProductReportResponse
}
var file_proto_productv1_product_proto_depIdxs = []int32{
	0, // 0: proto.GetProductListResponse.products:type_name -> proto.ProductData
	0, // 1: proto.GetProductSearchResponse.products:type_name -> proto.ProductData
	0, // 2: proto.GetProductReportResponse.products:type_name -> proto.ProductData
	1, // 3: proto.ProductService.GetProductList:input_type -> proto.GetProductListRequest
	3, // 4: proto.ProductService.GetProductSearch:input_type -> proto.GetProductSearchRequest
	5, // 5: proto.ProductService.GetProductPdfReport:input_type -> proto.GetProductReportRequest
	2, // 6: proto.ProductService.GetProductList:output_type -> proto.GetProductListResponse
	4, // 7: proto.ProductService.GetProductSearch:output_type -> proto.GetProductSearchResponse
	6, // 8: proto.ProductService.GetProductPdfReport:output_type -> proto.GetProductReportResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_productv1_product_proto_init() }
func file_proto_productv1_product_proto_init() {
	if File_proto_productv1_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_productv1_product_proto_rawDesc), len(file_proto_productv1_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_productv1_product_proto_goTypes,
		DependencyIndexes: file_proto_productv1_product_proto_depIdxs,
		MessageInfos:      file_proto_productv1_product_proto_msgTypes,
	}.Build()
	File_proto_productv1_product_proto = out.File
	file_proto_productv1_product_proto_goTypes = nil
	file_proto_productv1_product_proto_depIdxs = nil
}
