// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/mfav1/mfa.proto

package mfav1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	mfav1 "golang_grpc_mysql/proto/mfav1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// MfaServiceName is the fully-qualified name of the MfaService service.
	MfaServiceName = "proto.MfaService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MfaServiceMfaActivationProcedure is the fully-qualified name of the MfaService's MfaActivation
	// RPC.
	MfaServiceMfaActivationProcedure = "/proto.MfaService/MfaActivation"
	// MfaServiceMfaVerificationProcedure is the fully-qualified name of the MfaService's
	// MfaVerification RPC.
	MfaServiceMfaVerificationProcedure = "/proto.MfaService/MfaVerification"
)

// MfaServiceClient is a client for the proto.MfaService service.
type MfaServiceClient interface {
	MfaActivation(context.Context, *connect_go.Request[mfav1.MfaActivationRequest]) (*connect_go.Response[mfav1.MfaActivationResponse], error)
	MfaVerification(context.Context, *connect_go.Request[mfav1.MfaVerifyRequest]) (*connect_go.Response[mfav1.MfaVerifyResponse], error)
}

// NewMfaServiceClient constructs a client for the proto.MfaService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMfaServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) MfaServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &mfaServiceClient{
		mfaActivation: connect_go.NewClient[mfav1.MfaActivationRequest, mfav1.MfaActivationResponse](
			httpClient,
			baseURL+MfaServiceMfaActivationProcedure,
			opts...,
		),
		mfaVerification: connect_go.NewClient[mfav1.MfaVerifyRequest, mfav1.MfaVerifyResponse](
			httpClient,
			baseURL+MfaServiceMfaVerificationProcedure,
			opts...,
		),
	}
}

// mfaServiceClient implements MfaServiceClient.
type mfaServiceClient struct {
	mfaActivation   *connect_go.Client[mfav1.MfaActivationRequest, mfav1.MfaActivationResponse]
	mfaVerification *connect_go.Client[mfav1.MfaVerifyRequest, mfav1.MfaVerifyResponse]
}

// MfaActivation calls proto.MfaService.MfaActivation.
func (c *mfaServiceClient) MfaActivation(ctx context.Context, req *connect_go.Request[mfav1.MfaActivationRequest]) (*connect_go.Response[mfav1.MfaActivationResponse], error) {
	return c.mfaActivation.CallUnary(ctx, req)
}

// MfaVerification calls proto.MfaService.MfaVerification.
func (c *mfaServiceClient) MfaVerification(ctx context.Context, req *connect_go.Request[mfav1.MfaVerifyRequest]) (*connect_go.Response[mfav1.MfaVerifyResponse], error) {
	return c.mfaVerification.CallUnary(ctx, req)
}

// MfaServiceHandler is an implementation of the proto.MfaService service.
type MfaServiceHandler interface {
	MfaActivation(context.Context, *connect_go.Request[mfav1.MfaActivationRequest]) (*connect_go.Response[mfav1.MfaActivationResponse], error)
	MfaVerification(context.Context, *connect_go.Request[mfav1.MfaVerifyRequest]) (*connect_go.Response[mfav1.MfaVerifyResponse], error)
}

// NewMfaServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMfaServiceHandler(svc MfaServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mfaServiceMfaActivationHandler := connect_go.NewUnaryHandler(
		MfaServiceMfaActivationProcedure,
		svc.MfaActivation,
		opts...,
	)
	mfaServiceMfaVerificationHandler := connect_go.NewUnaryHandler(
		MfaServiceMfaVerificationProcedure,
		svc.MfaVerification,
		opts...,
	)
	return "/proto.MfaService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MfaServiceMfaActivationProcedure:
			mfaServiceMfaActivationHandler.ServeHTTP(w, r)
		case MfaServiceMfaVerificationProcedure:
			mfaServiceMfaVerificationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMfaServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMfaServiceHandler struct{}

func (UnimplementedMfaServiceHandler) MfaActivation(context.Context, *connect_go.Request[mfav1.MfaActivationRequest]) (*connect_go.Response[mfav1.MfaActivationResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("proto.MfaService.MfaActivation is not implemented"))
}

func (UnimplementedMfaServiceHandler) MfaVerification(context.Context, *connect_go.Request[mfav1.MfaVerifyRequest]) (*connect_go.Response[mfav1.MfaVerifyResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("proto.MfaService.MfaVerification is not implemented"))
}
