// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file userv1/user.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file userv1/user.proto.
 */
export const file_userv1_user: GenFile = /*@__PURE__*/
  fileDesc("ChF1c2VydjEvdXNlci5wcm90bxIFcHJvdG8i0QEKC1VzZXJQcm9maWxlEgoKAmlkGAEgASgJEhIKCmZpcnN0X25hbWUYAiABKAkSEQoJbGFzdF9uYW1lGAMgASgJEg0KBWVtYWlsGAQgASgJEg4KBm1vYmlsZRgFIAEoCRIQCgh1c2VybmFtZRgGIAEoCRIQCgh1c2VyX3BpYxgHIAEoCRIRCglpc19hY3RpdmUYCCABKAgSEgoKaXNfYmxvY2tlZBgJIAEoCBISCgptYWlsX3Rva2VuGAogASgJEhEKCXFyY29kZXVybBgLIAEoCSIcCg5HZXRVc2VyUmVxdWVzdBIKCgJpZBgBIAEoCSIzCg9HZXRVc2VyUmVzcG9uc2USIAoEdXNlchgBIAEoCzISLnByb3RvLlVzZXJQcm9maWxlIhQKEkdldEFsbFVzZXJzUmVxdWVzdCI4ChNHZXRBbGxVc2Vyc1Jlc3BvbnNlEiEKBXVzZXJzGAEgAygLMhIucHJvdG8uVXNlclByb2ZpbGUiWwoYVXBkYXRlVXNlclByb2ZpbGVSZXF1ZXN0EgoKAmlkGAEgASgJEhEKCWZpcnN0bmFtZRgCIAEoCRIQCghsYXN0bmFtZRgDIAEoCRIOCgZtb2JpbGUYBCABKAkiMQoZVXBkYXRlVXNlclByb2ZpbGVSZXNwb25zZRIUCgx0ZXh0X2NvbnRlbnQYASABKAkiNQoVQ2hhbmdlUGFzc3dvcmRSZXF1ZXN0EgoKAmlkGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJIi4KFkNoYW5nZVBhc3N3b3JkUmVzcG9uc2USFAoMdGV4dF9jb250ZW50GAEgASgJMrQCCgtVc2VyU2VydmljZRI4CgdHZXRVc2VyEhUucHJvdG8uR2V0VXNlclJlcXVlc3QaFi5wcm90by5HZXRVc2VyUmVzcG9uc2USRAoLR2V0QWxsVXNlcnMSGS5wcm90by5HZXRBbGxVc2Vyc1JlcXVlc3QaGi5wcm90by5HZXRBbGxVc2Vyc1Jlc3BvbnNlElYKEVVwZGF0ZVVzZXJQcm9maWxlEh8ucHJvdG8uVXBkYXRlVXNlclByb2ZpbGVSZXF1ZXN0GiAucHJvdG8uVXBkYXRlVXNlclByb2ZpbGVSZXNwb25zZRJNCg5DaGFuZ2VQYXNzd29yZBIcLnByb3RvLkNoYW5nZVBhc3N3b3JkUmVxdWVzdBodLnByb3RvLkNoYW5nZVBhc3N3b3JkUmVzcG9uc2VCcQoJY29tLnByb3RvQglVc2VyUHJvdG9QAVolZ29sYW5nX2dycGNfbXlzcWwvcHJvdG8vdXNlcnYxO3VzZXJ2MaICA1BYWKoCBVByb3RvygIFUHJvdG/iAhFQcm90b1xHUEJNZXRhZGF0YeoCBVByb3RvYgZwcm90bzM");

/**
 * @generated from message proto.UserProfile
 */
export type UserProfile = Message<"proto.UserProfile"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string first_name = 2;
   */
  firstName: string;

  /**
   * @generated from field: string last_name = 3;
   */
  lastName: string;

  /**
   * @generated from field: string email = 4;
   */
  email: string;

  /**
   * @generated from field: string mobile = 5;
   */
  mobile: string;

  /**
   * @generated from field: string username = 6;
   */
  username: string;

  /**
   * @generated from field: string user_pic = 7;
   */
  userPic: string;

  /**
   * @generated from field: bool is_active = 8;
   */
  isActive: boolean;

  /**
   * @generated from field: bool is_blocked = 9;
   */
  isBlocked: boolean;

  /**
   * @generated from field: string mail_token = 10;
   */
  mailToken: string;

  /**
   * @generated from field: string qrcodeurl = 11;
   */
  qrcodeurl: string;
};

/**
 * Describes the message proto.UserProfile.
 * Use `create(UserProfileSchema)` to create a new message.
 */
export const UserProfileSchema: GenMessage<UserProfile> = /*@__PURE__*/
  messageDesc(file_userv1_user, 0);

/**
 * @generated from message proto.GetUserRequest
 */
export type GetUserRequest = Message<"proto.GetUserRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message proto.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export const GetUserRequestSchema: GenMessage<GetUserRequest> = /*@__PURE__*/
  messageDesc(file_userv1_user, 1);

/**
 * @generated from message proto.GetUserResponse
 */
export type GetUserResponse = Message<"proto.GetUserResponse"> & {
  /**
   * @generated from field: proto.UserProfile user = 1;
   */
  user?: UserProfile;
};

/**
 * Describes the message proto.GetUserResponse.
 * Use `create(GetUserResponseSchema)` to create a new message.
 */
export const GetUserResponseSchema: GenMessage<GetUserResponse> = /*@__PURE__*/
  messageDesc(file_userv1_user, 2);

/**
 * @generated from message proto.GetAllUsersRequest
 */
export type GetAllUsersRequest = Message<"proto.GetAllUsersRequest"> & {
};

/**
 * Describes the message proto.GetAllUsersRequest.
 * Use `create(GetAllUsersRequestSchema)` to create a new message.
 */
export const GetAllUsersRequestSchema: GenMessage<GetAllUsersRequest> = /*@__PURE__*/
  messageDesc(file_userv1_user, 3);

/**
 * @generated from message proto.GetAllUsersResponse
 */
export type GetAllUsersResponse = Message<"proto.GetAllUsersResponse"> & {
  /**
   * @generated from field: repeated proto.UserProfile users = 1;
   */
  users: UserProfile[];
};

/**
 * Describes the message proto.GetAllUsersResponse.
 * Use `create(GetAllUsersResponseSchema)` to create a new message.
 */
export const GetAllUsersResponseSchema: GenMessage<GetAllUsersResponse> = /*@__PURE__*/
  messageDesc(file_userv1_user, 4);

/**
 * @generated from message proto.UpdateUserProfileRequest
 */
export type UpdateUserProfileRequest = Message<"proto.UpdateUserProfileRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string firstname = 2;
   */
  firstname: string;

  /**
   * @generated from field: string lastname = 3;
   */
  lastname: string;

  /**
   * @generated from field: string mobile = 4;
   */
  mobile: string;
};

/**
 * Describes the message proto.UpdateUserProfileRequest.
 * Use `create(UpdateUserProfileRequestSchema)` to create a new message.
 */
export const UpdateUserProfileRequestSchema: GenMessage<UpdateUserProfileRequest> = /*@__PURE__*/
  messageDesc(file_userv1_user, 5);

/**
 * @generated from message proto.UpdateUserProfileResponse
 */
export type UpdateUserProfileResponse = Message<"proto.UpdateUserProfileResponse"> & {
  /**
   * @generated from field: string text_content = 1;
   */
  textContent: string;
};

/**
 * Describes the message proto.UpdateUserProfileResponse.
 * Use `create(UpdateUserProfileResponseSchema)` to create a new message.
 */
export const UpdateUserProfileResponseSchema: GenMessage<UpdateUserProfileResponse> = /*@__PURE__*/
  messageDesc(file_userv1_user, 6);

/**
 * @generated from message proto.ChangePasswordRequest
 */
export type ChangePasswordRequest = Message<"proto.ChangePasswordRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message proto.ChangePasswordRequest.
 * Use `create(ChangePasswordRequestSchema)` to create a new message.
 */
export const ChangePasswordRequestSchema: GenMessage<ChangePasswordRequest> = /*@__PURE__*/
  messageDesc(file_userv1_user, 7);

/**
 * @generated from message proto.ChangePasswordResponse
 */
export type ChangePasswordResponse = Message<"proto.ChangePasswordResponse"> & {
  /**
   * @generated from field: string text_content = 1;
   */
  textContent: string;
};

/**
 * Describes the message proto.ChangePasswordResponse.
 * Use `create(ChangePasswordResponseSchema)` to create a new message.
 */
export const ChangePasswordResponseSchema: GenMessage<ChangePasswordResponse> = /*@__PURE__*/
  messageDesc(file_userv1_user, 8);

/**
 * @generated from service proto.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc proto.UserService.GetUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof GetUserRequestSchema;
    output: typeof GetUserResponseSchema;
  },
  /**
   * @generated from rpc proto.UserService.GetAllUsers
   */
  getAllUsers: {
    methodKind: "unary";
    input: typeof GetAllUsersRequestSchema;
    output: typeof GetAllUsersResponseSchema;
  },
  /**
   * @generated from rpc proto.UserService.UpdateUserProfile
   */
  updateUserProfile: {
    methodKind: "unary";
    input: typeof UpdateUserProfileRequestSchema;
    output: typeof UpdateUserProfileResponseSchema;
  },
  /**
   * @generated from rpc proto.UserService.ChangePassword
   */
  changePassword: {
    methodKind: "unary";
    input: typeof ChangePasswordRequestSchema;
    output: typeof ChangePasswordResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_userv1_user, 0);

